services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
    volumes:
      - minio-data:/data
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://0.0.0.0:9000/minio/health/live"]
      interval: 30s
      timeout: 10s
      retries: 5

  create-buckets:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc alias set myminio http://minio:9000 username password)
      do sleep 1; 
      done;
      /usr/bin/mc mb myminio/photos myminio/videos;
      /usr/bin/mc anonymous set public myminio/photos;
      /usr/bin/mc anonymous set public myminio/videos;
      "
volumes:
  minio-data:
    driver: local